#!/usr/bin/env bash
# ============================================================================= #
#  ➜ ➜ ➜ TRAP
# ============================================================================= #
trap 'exit' SIGINT SIGQUIT SIGTSTP

if [ ! -z "$TERM" ]; then
    export TERM="xterm-256color"
fi

if [ ! -f "lib/utilities.sh" ]; then

    git submodule --quiet sync --recursive
    git submodule --quiet foreach --recursive git fetch
    git submodule --quiet update --init --recursive
fi
cd lib || exit 1
git checkout master
git pull -q origin master
cd .. || exit 1

source "lib/utilities.sh"

main() {
    TITLE "Device:"
    CUTLINE
    BOLDBLUE "$DISTRO | $UARCH | $UKERNEL"
    CUTLINE

    TITLE "Running auto install"
    CUTLINE
    ./bin/dosync
    CUTLINE
    exec "zsh"
    exit 0
}
while true; do
    main "$@"
done
