#!/usr/bin/env bash

if [ ! -f 'lib/utilities.sh' ]; then
    git submodule --quiet sync --recursive
    git submodule --quiet update --init --recursive

    cd lib
    git checkout master
    cd ..
fi
DOTFILES_ROOT="$(pwd -P)"
current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$current_dir/lib/utilities.sh"

prepare_env() {
    export DOTFILES=".dotfiles"
    export TERM="xterm-256color"
}
get_file() {
    srcfile="$(echo $file | awk -F: '{print $1}')"
    dstfile="$(echo $file | awk -F: '{print $2}')"
    dotsrc="$HOME/$DOTFILES/$srcfile"

    if [[ $dstfile = "" ]]; then
        dstfile=".$(basename "$srcfile")"
    fi
    dotfile="$HOME/$dstfile"
}
run_install() {
    syncrc="syncrc"
    srcfiles="$(sed -n '/\[files\]/,/\[endfiles\]/p' $syncrc | grep -v '^\[.*files]' | grep -v ^#)"
    if [[ -z "$srcfiles" ]]; then
        echo "Specify files to sync in syncrc file"
        exit 1
    fi
    for file in $srcfiles; do
        get_file "$file"
        SYMLINK_INTERACTIVE "$dotsrc" "$dotfile"
    done

}
install_fonts() {
    if [ ! -d "$HOME/.local/share/fonts" ]; then

        NOTIFY "Installing fonts"

        git clone https://github.com/powerline/fonts.git --depth=1
        cd fonts
        ./install.sh
        cd ..
        rm -rf fonts

        #      git clone --depth=1 https://github.com/romkatv/nerd-fonts.git
        #      cd nerd-fonts
        #      ./build 'Meslo/S/*'
        #      cd ..
        #      rm -rf nerd-fonts
    fi
}

main() {
    TITLE "Running auto install"

    prepare_env "$@"
    run_install "$@"
    exit 0

}
while true; do
    main "$@"
done
