#!/usr/bin/env bash
# ============================================================================= #
#  ➜ ➜ ➜ TRAP
# ============================================================================= #
trap exit SIGINT SIGQUIT SIGTSTP

update_repo() {
    git submodule --quiet sync --recursive
    git submodule --quiet update --init --recursive
}

prepare_env() {
    source "lib/utilities.sh"

    TITLE "Device:"
    CUTLINE
    BOLDBLUE "$DISTRO | $UARCH | $UKERNEL"
    CUTLINE

}

main() {
    update_repo
    prepare_env

    TITLE "Running auto install"
    CUTLINE
    ./bin/dosync
    CUTLINE
    exec "zsh"
    exit 0
}
while true; do
    main "$@"
done
